/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MRubyState */

#ifndef _Included_MRubyState
#define _Included_MRubyState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MRubyState
 * Method:    getStatePointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MRubyState_getStatePointer
  (JNIEnv *, jobject);

/*
* Class:     MRubyState
* Method:    loadClassToState
* Signature: (JLjava/lang/String;Ljava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_MRubyState_loadClassToState
(JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     MRubyState
 * Method:    loadClassMethodsToState
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_MRubyState_loadClassMethodsToState
  (JNIEnv *, jobject, jlong, jstring, jstring, jobjectArray, jobjectArray, jobjectArray, jbooleanArray);

/*
 * Class:     MRubyState
 * Method:    loadString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MRubyState_loadString
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     MRubyState
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MRubyState_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
